/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IDnnPersonaBarUtilities } from "./dnn/types";
export { IDnnPersonaBarUtilities } from "./dnn/types";
export namespace Components {
  interface MyAppRoot {
    /**
      * The persona bar utilites.
     */
    "util": IDnnPersonaBarUtilities;
    /**
      * The wrapping html element.
     */
    "wrapper": HTMLElement;
  }
}
declare global {
  interface HTMLMyAppRootElement extends Components.MyAppRoot, HTMLStencilElement {
  }
  var HTMLMyAppRootElement: {
    prototype: HTMLMyAppRootElement;
    new(): HTMLMyAppRootElement;
  };
  interface HTMLElementTagNameMap {
    "my-app-root": HTMLMyAppRootElement;
  }
}
declare namespace LocalJSX {
  interface MyAppRoot {
    /**
      * The persona bar utilites.
     */
    "util"?: IDnnPersonaBarUtilities;
    /**
      * The wrapping html element.
     */
    "wrapper"?: HTMLElement;
  }
  interface IntrinsicElements {
    "my-app-root": MyAppRoot;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "my-app-root": LocalJSX.MyAppRoot & JSXBase.HTMLAttributes<HTMLMyAppRootElement>;
    }
  }
}
