//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $ext_rootnamespace$.ViewModels
{
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// A viewmodel that exposes all resource keys in strong types.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class LocalizationViewModel
    {
        /// <summary>
        /// Localized strings present the ModelValidation resources.
        /// </summary>
        public ModelValidationInfo ModelValidation { get; set; }

        /// <summary>
        /// Localized strings present the UI resources.
        /// </summary>
        public UIInfo UI { get; set; }
        /// <summary>
        /// Localized strings for the ModelValidation resources.
        /// </summary>
        public class ModelValidationInfo
        {
            /// <summary>Gets or sets the IdGreaterThanZero localized text.</summary>
            /// <example>The Id must be an integer bigger than 0</example>
            public string IdGreaterThanZero { get; set; }

            /// <summary>Gets or sets the NameRequired localized text.</summary>
            /// <example>The name is required</example>
            public string NameRequired { get; set; }


        }

        /// <summary>
        /// Localized strings for the UI resources.
        /// </summary>
        public class UIInfo
        {
            /// <summary>Gets or sets the AddItem localized text.</summary>
            /// <example>Add Item</example>
            public string AddItem { get; set; }

            /// <summary>Gets or sets the Cancel localized text.</summary>
            /// <example>Cancel</example>
            public string Cancel { get; set; }

            /// <summary>Gets or sets the Create localized text.</summary>
            /// <example>Create</example>
            public string Create { get; set; }

            /// <summary>Gets or sets the Delete localized text.</summary>
            /// <example>Delete</example>
            public string Delete { get; set; }

            /// <summary>Gets or sets the DeleteItemConfirm localized text.</summary>
            /// <example>Are you sure you want to delete this item?</example>
            public string DeleteItemConfirm { get; set; }

            /// <summary>Gets or sets the Description localized text.</summary>
            /// <example>Description</example>
            public string Description { get; set; }

            /// <summary>Gets or sets the Edit localized text.</summary>
            /// <example>Edit</example>
            public string Edit { get; set; }

            /// <summary>Gets or sets the LoadMore localized text.</summary>
            /// <example>Load More</example>
            public string LoadMore { get; set; }

            /// <summary>Gets or sets the Name localized text.</summary>
            /// <example>Name</example>
            public string Name { get; set; }

            /// <summary>Gets or sets the No localized text.</summary>
            /// <example>No</example>
            public string No { get; set; }

            /// <summary>Gets or sets the Save localized text.</summary>
            /// <example>Save</example>
            public string Save { get; set; }

            /// <summary>Gets or sets the SearchPlaceholder localized text.</summary>
            /// <example>Search</example>
            public string SearchPlaceholder { get; set; }

            /// <summary>Gets or sets the ShownItems localized text.</summary>
            /// <example>Showing {0} of {1} items.</example>
            public string ShownItems { get; set; }

            /// <summary>Gets or sets the Yes localized text.</summary>
            /// <example>Yes</example>
            public string Yes { get; set; }


        }


    }
}